testmode: false
enable_alert: false
ignore_tags: ["other_gpu", "others_gpu"]  # 増えるようだったらfnmatchで対応する
wandb_dir: /tmp/wandb
max_workers: 1

dashboard:
  entity: geniac-gpu
  project: gpu-dashboard2
  # project: gpu-dashboard2-dev  # for development
  tag_for_latest: latest

dataset:
  entity: geniac-gpu
  project: gpu-dashboard2
  artifact_name: all_runs_data

blacklist:
  entity: geniac-gpu
  project: gpu-dashboard2
  artifact_name: blacklist

companies:
# ### 第一弾企業 ###
#   ### ABEJA ###
#   - company: abeja-geniac 
#     teams:
#       - abeja-geniac
#     schedule:
#       - date: "2024-02-15"
#         assigned_gpu_node: 48
#       - date: "2024-04-15" # end of GPU provision
#         assigned_gpu_node: 0

#   ### PFE ###
#   - company: pfe-geniac 
#     teams:
#       - pfe-geniac
#     schedule:
#       - date: "2024-02-15"
#         assigned_gpu_node: 50
#       - date: "2024-07-16"
#         assigned_gpu_node: 52

#   ### Stockmark ###
#   - company: stockmark-geniac 
#     teams:
#       - stockmark-geniac
#     schedule:
#       - date: "2024-02-15"
#         assigned_gpu_node: 48
#       - date: "2024-04-15" # end of GPU provision
#         assigned_gpu_node: 0
#     ignore_project_pattern: "100b"

#   ### Turing ###
#   - company: turing-geniac 
#     teams:
#       - turing-geniac
#     schedule:
#       - date: "2024-02-15"
#         assigned_gpu_node: 4
#       - date: "2024-06-15"
#         assigned_gpu_node: 35
#     distributed_learning: true

#   ### NII ###
#   - company: nii-geniac 
#     teams:
#       - nii-geniac
#     schedule:
#       - date: "2024-04-15"
#         assigned_gpu_node: 75
#     distributed_learning: true
#     ignore_project_pattern: "*-dummy"

#   ### Matsuo LB ###
#   - company: weblab-geniac 
#     teams:
#       - weblab-geniac1
#       - weblab-geniac2
#       - weblab-geniac3
#       - weblab-geniac4
#       - weblab-geniac5
#       - weblab-geniac6
#       - weblab-geniac7
#       - weblab-geniac8
#     schedule:
#       - date: "2024-04-15"
#         assigned_gpu_node: 21

#   ### Sakana AI ###
#   - company: sakanaai-geniac 
#     teams:
#       - sakanaai-geniac
#     schedule:
#       - date: "2024-06-15"
#         assigned_gpu_node: 32

#   ### ELYZA ###
#   - company: elyza-geniac
#     teams:
#       - elyza-geniac
#     schedule:
#       - date: "2024-05-24"
#         assigned_gpu_node: 36
#     distributed_learning: true

#   ### Kotoba Technologies ###
#   - company: kotoba-geniac
#     teams:
#       - kotoba-geniac
#     schedule:
#       - date: "2024-05-24"
#         assigned_gpu_node: 8
#     distributed_learning: true

#   ### 富士通 ###
#   - company: fujitsu-geniac
#     teams:
#       - fujitsu-geniac
#     schedule:
#       - date: "2024-05-24"
#         assigned_gpu_node: 16
#     distributed_learning: true


### 第二弾企業 ###
  ### ABEJA ###
  - company: abeja-geniac
    teams:
      - abeja-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 6
    distributed_learning: false

  ### AIdeaLab ###
  - company: aidealab-geniac
    teams:
      - aidealab-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 2
    distributed_learning: false

  ### AiHUB ###
  - company: aihub-geniac
    teams:
      - aihub-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 5
    distributed_learning: false

  ### AI inside ###
  - company: aiinside-geniac
    teams:
      - aiinside-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 3
    distributed_learning: false

  ### EQUES ###
  - company: eques-geniac
    teams:
      - eques-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 1
    distributed_learning: false

  ### Kotoba Technologies Japan ###
  - company: kotoba-geniac
    teams:
      - kotoba-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 29
    distributed_learning: false

  ### NABLAS ###
  - company: nablas-geniac
    teams:
      - nablas-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 4
    distributed_learning: false

  ### SyntheticGestalt ###
  - company: syntheticgestalt-geniac
    teams:
      - syntheticgestalt-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 0
    distributed_learning: false

  ### オルツ ###
  - company: alt-geniac
    teams:
      - alt-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 0
    distributed_learning: false

  ### 国立研究開発法人海洋研究開発機構 ###
  - company: jamstec-geniac
    teams:
      - jamstec-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 2
    distributed_learning: false

  ### カラクリ ###
  - company: karakuri-geniac
    teams:
      - karakuri-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 24
    distributed_learning: false

  ### ストックマーク ###
  - company: stockmark-geniac
    teams:
      - stockmark-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 42
    distributed_learning: false

  ### データグリッド ###
  - company: datagrid-geniac
    teams:
      - datagrid-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 16
    distributed_learning: false

  ### ヒューマノーム研究所 ###
  - company: humanome-geniac
    teams:
      - humanome-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 4
    distributed_learning: false

  ### フューチャー研究所 ###
  - company: future-geniac
    teams:
      - future-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 4
    distributed_learning: false

  ### リコー ###
  - company: ricoh-geniac
    teams:
      - ricoh-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 8
    distributed_learning: false

  ### ユビタス ###
  - company: ubitus-geniac
    teams:
      - ubitus-geniac
    schedule:
      - date: "2024-10-24"
        assigned_gpu_node: 32
    distributed_learning: false