name: Docker Build & Push to Amazon ECR (Run Existence Check)

on:
  push:
    branches: [main]
    paths:
      - 'src/uploader/run_existence_checker.py'
      - 'src/**'
      - 'requirements.txt'
      - 'config.yaml'
      - 'Dockerfile.run_existence_check'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: gpu-dashboard-run-existence-check
  DOCKERFILE: Dockerfile.run_existence_check

jobs:
  build-and-push:
    name: Build and Push to Amazon ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest -f ${{ env.DOCKERFILE }} .
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest